title = "Palestine Ref"

[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
description = "This page lists links to resources that tell the other side of the Palestinan-Israeli story. This page doesn't endorse any of the links below, it merely curates content that represents the other opinion that is usually suppressed."
  [params.theme_config]
    appearance = "light"
    back_home_text = "Back to main page"
    date_format = "2006-01-02"
    show_description = true