name: Docker Build URL Validator

on: 
  push:
    paths:
      - 'UrlValidator/**'
env:
  DOCKER_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/url-validator:${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./UrlValidator
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}

      - name: Retag image as latest if on default branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            docker tag ${{ env.DOCKER_IMAGE_NAME }} docker.pkg.github.com/${{ github.repository }}/url-validator:latest
            docker push docker.pkg.github.com/${{ github.repository }}/url-validator:latest
          fi