name: Validate URLs

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch: 

env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}/url-validator:main

jobs:
  run-docker-container:
    name: Run Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker container
        run: docker run --name validator-instance ${{ env.DOCKER_IMAGE_NAME }} https://palestine-ref.info