name: Validate URLs

on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  run-docker-container:
    name: Run Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker container
        run: docker run --name validator-instance ${{ env.DOCKER_IMAGE_NAME }} https://palestine-ref.info